# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  force
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            -
    exception:
        enabled: true
        messages: { App\Exception\RessourceException: true }
        codes: { App\Exception\RessourceException: 400, \Exception: 429 }
