nelmio_api_doc:
    documentation:
        info:
            title: Bilemo !
            description: Api for Openclassrooms project.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                ApiKeyAuth:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - Bearer: []
            - ApiKeyAuth: []
    areas: # to filter documented areas
        path_patterns:
            - /api/v1
            - /v1/