security:
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email
        customers:
            entity:
                class: App\Entity\Customer
                property: email
        chain_provider:
            chain:
                providers: [ 'users', 'customers' ]

    encoders:
        App\Entity\User:
            algorithm: auto

        App\Entity\Customer:
            algorithm: auto
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            provider: users
            anonymous: true
            json_login:
                username_path: email
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            provider: users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1,  roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
