version: '2'

services:
  myapp:
    image: 'bilemo'
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/src/myapp
      - /var/run/php/php7.4-fpm.sock
    depends_on:
      - mysql
  mysql:
    image: 'mysql'
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
       MYSQL_HOST: mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
  nginx:
    image: 'nginx:latest'
    depends_on:
      - myapp
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/myapp
      - /var/run/php/php7.4-fpm.sock
