version: '2'

services:
  myapp:
    image: 'bilemo'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/myapp'
    depends_on:
      - mysql
  mysql:
    image: 'mysql'
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
       MYSQL_HOST: mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
